version: "3"
services:
  app:
    build: .
    ports:
    - "8000:8000"
    command: php artisan serve --host 0.0.0.0
    environment:
    - DB_HOST=mysql
    - DATABASE_URL=mysql://root:password@mysql/memory?charset=utf8mb4
    - REDIS_URL=redis:6379
    - REDIS_HOST=redis
    volumes:
    - .:/var/www/html
  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: memory
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis
    ports:
    - "6379:6379"
    command: redis-server --appendonly yes --requirepass foobared
